.TH ELECTRUMSRVD 1 "April 2026" "Electrumsrvd" "Electrumsrvd"
.SH NAME
electrumsrvd \- A lightweight Electrum server
.SH SYNOPSIS
.B electrumsrvd
[\-c
.I config_file
][\-l
.I log_level
][\-d]
.SH DESCRIPTION
.IR electrumsrvd
is a lightweight Electrum server that provides a simple and efficient way to run your own Electrum node. It offers various options to configure its behavior and operation.
.SH OPTIONS
.TP
.B \-c
.I config_file
Specifies the path to the configuration file. The default path is
.IR /usr/local/etc/electrumsrvd.conf .
.TP
.B \-l
.I log_level
Sets the log level for
.IR electrumsrvd
. The log level can be one of the following: debug, info, or error.
.TP
.B \-d
Detaches the process and runs
.IR electrumsrvd
as a daemon in the background.
.SH EXAMPLES
.Start
.IR electrumsrvd
with default configuration and log level:
.sp
.ft B
electrumsrvd
.ft
.sp
.Start
.IR electrumsrvd
with a custom configuration file and log level set to debug:
.sp
.ft B
electrumsrvd -c /path/to/custom.conf -l debug
.ft
.sp
.Start
.IR electrumsrvd
as a daemon with default configuration:
.sp
.ft B
electrumsrvd -d
.ft
.SH NOTES
Requires
.B txindex
enabled.

.SH TUNING
On ZFS file systems, the leveldb database may experiance a write stall if not correctly configured, tehrefore it is reccomended to create a separate zfs dataset:
.TP
zfs create <poolname>/electrumsrvd
creates the new separate dataset

Once the dataset is created the following configurations are reccomended

.TP
zfs set atime=off <poolname>/electrumsrvd
Turning	this property off avoids producing write traffic  when reading files and can result in significant performance gains.
.TP
zfs set recordsize=8K <poolname>/electrumsrvd
Matches the zfs dataset recordsize value with the 
.I electrumsrvd
db blocksize
.TP
zfs set sync=disabled <poolname>/electrumsrvd
File system transactions are only committed to stable storage periodically

.SH AUTHOR
rpmodell (rpmodell@proton.me)
.SH SEE ALSO
.IR electrumsrvd.conf (5)
