.TH ELECTRUMD.CONF 5 "April 2026" "electrumd.conf" "Electrumd Configuration File"
.SH NAME
electrumd.conf \- Configuration file for electrumd
.SH DESCRIPTION
The
.I electrumd.conf
file is used to configure the
.B electrumd
server, a lightweight Electrum server.
.SH OPTIONS
The following options can be set in the
.I electrumd.conf
file:
.TP
.B log_file_path=<custom log path>
Set a custom path for the log file. Default is
.I /var/log/electrumd.log
.TP
.B pid_file_path=<custom pid path>
Set a custom path for the PID file. Default is
.I /var/log/electrumd.pid
.TP
.B db_dir=<db_dir_path>
Set the directory for the database. This setting is mandatory and does not have a default.
.TP
.B cache_size=<size>
Set the maximum RAM cache size for fetched blocks before flushing to disk. Can be specified in bytes, 
megabytes (M), kilobytes (K), or gigabytes (G). Default is 4096 bytes. Default is 192MB
.TP
.B bitcoind_rpc_cookie_file=<path>
Path to the Bitcoin daemon RPC cookie file. Either this or
.B bitcoind_rpc_auth
is mandatory.
.TP
.B bitcoind_rpc_auth=<rpc_user:rpc_password>
Bitcoin daemon RPC user and password. Note: the cookie file and password options are mutually exclusive, and at least one auth method is mandatory.
.TP
.B bitcoind_rpc_host=<host:port>
Default bind address and port of Bitcoin daemon RPC. Default is
.I localhost:8332
.TP
.B electrumd_rpc_bind=<host>
Bind address for electrumd to listen for incoming connections. Default is
.I localhost
.TP
.B electrumd_rpc_port=<port>
Bind port for electrumd to listen on.
.TP
.B bitcoind_p2p_addr=<addr>
Bitcoind P2P address.
.TP
.B bitcoind_p2p_port=<port>
Bitcoind P2P port.
.TP
.B donation_address=<donation_addr>
Donation address for the electrumd server.
.TP
.B banner=<banner>
Banner message for the electrumd server.
.TP
.B electrumd_rpc_ssl=<yes|no>
Enable or disable SSL/TLS encryption for the RPC interface. When enabled, the electrumd_rpc_ssl_cert_file 
and electrumd_rpc_ssl_priv_key_file paths must also be specified.
.TP
.B electrumd_rpc_ssl_cert_file=<ssl_cert_file>
The SSL certificate file path. The certificate file must be in unencrypted PEM format
.TP
.B electrumd_rpc_ssl_priv_key_file=<private_key_file>
The SSL private key file path. The private key file must be in unencrypted PEM format
.SH AUTHOR
rpmodell (rpmodell@proton.me)
.SH SEE ALSO
.B electrumd(1)
