#
# This file is an example configuration for electrumd (the tiny electrum 
# server)
#
# The path to the Bitcoin daemon rpc cookie file
# bitcoind_rpc_cookie_file=<path>
#
# Bitcoin daemon rpc user and password. Note: the cookie file and pasword 
# options are mutually exclusive and at least one auth method is mandatory
# bitcoind_rpc_auth=<rpc_user:rpc_password>
#
# The default bind address and port of Bitcoin daemon rpc. Default is localhost:8332
# bitcoind_rpc_host=<host:port>
#
# The bind address on which electrumd listens for incoming connections. Default is localhost
# electrumd_rpc_bind=<host>
# 
# The bind port on which electrumd listens to
# electrumd_rpc_port=<port>
#
# Bitcoind p2p port address and port
# bitcoind_p2p_addr=<addr>
# bitcoind_p2p_port=<port>
#
# The maximum ram cache for fetched blocks before flushing to disk in bytes. Default is 4096 bytes.
cache_size=128M
