# This file is an example configuration for electrumd (the tiny Electrum server)
#
# Log path settings
# Default log path is /var/log/electrumd.log
# log_file_path=<custom log path>
#
# PID file path settings
# Default PID file path is /var/log/electrumd.pid
# pid_file_path=<custom pid path>
#
# Database directory and cache settings
# Database directory is mandatory and does not have a default.
# db_dir=/var/db/electrumd/
#
# Maximum RAM cache size for fetched blocks before flushing to disk. Can be specified in 
# bytes, kilobytes (K), megabytes (M), or gigabytes (G). Default is 128 megabytes.
# It is reccomended to use a multiple of 12 as the cache amount is splitted between three
# databases.
# cache_size=192M
#
# Bitcoin daemon RPC settings
# Path to the Bitcoin daemon RPC cookie file. Either this or 'bitcoind_rpc_auth' is mandatory.
# bitcoind_rpc_cookie_file=<path>
#
# Bitcoin daemon RPC user and password. Note: the cookie file and password options are mutually exclusive, and 
# at least one auth method is mandatory.
# bitcoind_rpc_auth=<rpc_user:rpc_password>
#
# Default bind address and port of Bitcoin daemon RPC. Default is localhost:8332
# bitcoind_rpc_host=<host:port>
#
# Electrumd RPC settings
# Bind address for electrumd to listen for incoming connections. Default is localhost
# electrumd_rpc_bind=<host>
#
# Bind port for electrumd to listen on
# electrumd_rpc_port=<port>
# 
# Enables electrumd to listen on SSL socket
# electrumd_listen_ssl=<yes|no>
# electrumd_ssl_cert_file=<ssl_cert_file>
# electrumd_ssl_priv_key_file=<private_key_file>
#
# Bitcoind P2P settings
# Bitcoind P2P address and port
# bitcoind_p2p_addr=<addr>
# bitcoind_p2p_port=<port>
#
# Donation address for the electrumd server
# donation_address=<donation_addr>
#
# Banner message for the electrumd server
# banner=<banner>
